### ISSUE TITLE
Glacio ore generated in the Overworld

### ISSUE THREAD

**Issue by vizthex123** [Mrthomas20121-Mods/Thermal-And-Space#6]
Haven't seen this before, so I think it's only an issue with Glacio ores (but I could be wrong).
![2024-05-20_19 41 22](https://github.com/Mrthomas20121-Mods/Thermal-And-Space/assets/31721920/41aafa57-85fd-4f96-963e-3071ded6a786)

Log if it helps:
[latest.log](https://github.com/Mrthomas20121-Mods/Thermal-And-Space/files/15382908/latest.log)

And the one from when I made the world:
[2024-05-20-1.log.gz](https://github.com/Mrthomas20121-Mods/Thermal-And-Space/files/15382911/2024-05-20-1.log.gz)

**Comment by Mrthomas20121** [comment]
i'll look into it.

**Comment by vizthex123** [comment]
noice.

**Comment by vizthex123** [comment]
Is there an ETA on this being fixed in the 1.20.1 version?
