### ISSUE TITLE
Ores don't have the proper mining requirements

### ISSUE THREAD

**Issue by vizthex123** [Mrthomas20121-Mods/Thermal-And-Space#7]
For example, Nickel needs an Iron tool, but the modded ores don't have the block tag for it
![image](https://github.com/Mrthomas20121-Mods/Thermal-And-Space/assets/31721920/b63668b0-72e7-4e17-9dae-f5945d98f72e)

Modded one:
![image](https://github.com/Mrthomas20121-Mods/Thermal-And-Space/assets/31721920/3858344d-2ece-4919-b56f-6acb60fb2a7e)

I checked all the ores and it's the same across the board: None of them have the correct mining level tag.

**Comment by Mrthomas20121** [comment]
i'll fix it

**Comment by vizthex123** [comment]
noice, thanks.
